# Theme settings
doks:
    baseurl:
    color_theme: red # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: Learn EO
            image:
#        nav:
#            - item_name: Item 1
#              item_url: '#'
#            - item_name: Item 2
#              item_url: '#'
#            - item_name: Item 3
#              item_url: '#'
    footer:
        content:
            logo:
                text: A project of OpenSpaceData.org
                image:
            copyright: Except where otherwise noted, content on this site is licensed under a Creative Commons Attribution 4.0 International license.
        social_list:
            - network_name: home
              profile_url: 'https://www.openspacedata.org/'
            - network_name: twitter
              profile_url: 'https://twitter.com/openspacedata1'
            - network_name: github
              profile_url: 'https://github.com/OpenSpaceData'
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md' ]
permalink: /:title/

plugins:
  - "jekyll-github-metadata"

repository: OpenSpaceData/learn.openspacedata.org

github:
  source:
    branch: master